### ISSUE TITLE
Unable to connect http://localhost:10080/fd

### ISSUE THREAD

**Issue by fruisoft** [hrektts/docker-fusiondirectory#4]
Hi, I've used your docker-compose.yml, containers are running but can't connect to http://localhost:10080/fd  -> response is Unable to connect

Trying http://localhost:10080 -> response is 404 Not Found. nginx/1.13.3

Looking fusiondirectory log, only has this lines:
fusiondirectory_1  | Starting FusionDirectory ... 
fusiondirectory_1  | 
fusiondirectory_1  | LDAP_ADMIN_DN is not defined and set to 'cn=admin,dc=example,dc=org'
fusiondirectory_1  | Checking FusionDirectory's config file
fusiondirectory_1  | /etc/fusiondirectory/fusiondirectory.conf exists…
fusiondirectory_1  | Rights on /etc/fusiondirectory/fusiondirectory.conf are correct

Can you help me?

Thanks in advance ;)

**Comment by hrektts** [comment]
Hi, could you try http://localhost:10080/fd/ ? The difference is the trailing slash.

**Comment by fruisoft** [comment]
Oh my god !! excuse my awkwardness !! Thanks for your rapid response. Solved !! :)
