### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by Dioven15** [hrektts/docker-fusiondirectory#5]
just followed the installation instructions on the repo and after i run it, it displays 404 not found nginx/1.13.3

**Comment by fruisoft** [comment]
Hi, could you try http://localhost:10080/fd/ ? The difference is the trailing slash.

**Comment by Dioven15** [comment]
oh thanks man! i tried using  http://localhost:10080/fd earlier without the slash on the end..

**Comment by fruisoft** [comment]
Yes, I had the same problem !! :-) 
Regards
